#!/bin/bash --login
cd $(dirname $0)/../..

. _CI/scripts/bootstrap


cd graphs
pyreverse -o png -A -f PUB_ONLY -p graphs ../{{cookiecutter.project_slug}}

echo "You should have class and package graphs under the graphs directory"
