#!/bin/bash --login
# we want all these files to exist in the actual package
required_files=(".VERSION" "LICENSE" "AUTHORS.rst" "CONTRIBUTING.rst" "HISTORY.rst" "README.rst" "USAGE.rst")

cd $(dirname $0)/../..

. _CI/scripts/bootstrap
set -e

# cleaning up directories if exist
rm -rf build dist

# copy files in the structure
for file in "${required_files[@]}"
    do
        cp $file {{cookiecutter.project_slug}}/$file
    done

# package and upload
python setup.py sdist bdist_egg  upload -r pypi

# remove files from the structure
for file in "${required_files[@]}"
    do
        rm {{cookiecutter.project_slug}}/$file
    done
