#!/bin/bash
cd $(dirname $0)/../..

source $(which virtualenvwrapper.sh)

[ -z "$WORKON_HOME" ] && WORKON_HOME=$HOME/.virtualenvs

if (! test -d "$WORKON_HOME/{{ cookiecutter.repo_name }}")
then
  echo "Creating virtual env for {{ cookiecutter.repo_name }}"
  if (! mkvirtualenv "{{ cookiecutter.repo_name }}" )
  then
    echo "Missing prerequisite virtualenvwrapper, bailing out"
    exit 1
  fi
fi

echo "Working on virtualenv {{ cookiecutter.repo_name }}"
source "$WORKON_HOME/{{ cookiecutter.repo_name }}/bin/activate"

echo "Installing python package requirements.."
pip install -r requirements.txt
